# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: crypto/insight/v1/insight.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'crypto/insight/v1/insight.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63rypto/insight/v1/insight.proto\x12\x11\x63rypto.insight.v1\"2\n\x11GetInsightRequest\x12\x0f\n\x07\x63oin_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ys\x18\x02 \x01(\x05\"\\\n\x12GetInsightResponse\x12\x0f\n\x07\x63oin_id\x18\x01 \x01(\t\x12\x0f\n\x07insight\x18\x02 \x01(\t\x12\x14\n\x0cgenerated_at\x18\x03 \x01(\t\x12\x0e\n\x06\x63\x61\x63hed\x18\x04 \x01(\x08\x32k\n\x0eInsightService\x12Y\n\nGetInsight\x12$.crypto.insight.v1.GetInsightRequest\x1a%.crypto.insight.v1.GetInsightResponseB\x03\x90\x01\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crypto.insight.v1.insight_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\220\001\000'
  _globals['_GETINSIGHTREQUEST']._serialized_start=54
  _globals['_GETINSIGHTREQUEST']._serialized_end=104
  _globals['_GETINSIGHTRESPONSE']._serialized_start=106
  _globals['_GETINSIGHTRESPONSE']._serialized_end=198
  _globals['_INSIGHTSERVICE']._serialized_start=200
  _globals['_INSIGHTSERVICE']._serialized_end=307
# @@protoc_insertion_point(module_scope)
