# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc_generated.crypto.insight.v1 import insight_pb2 as crypto_dot_insight_dot_v1_dot_insight__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in crypto/insight/v1/insight_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InsightServiceStub(object):
    """InsightService generates AI-powered price trend analysis for cryptocurrencies.

    Dual-protocol pattern: this service is exposed via both:
    gRPC  — port 50051 (this file)
    REST  — port 8000  (FastAPI /api/v1/cryptocurrencies/{coin_id}/insight)

    Both transports share identical business logic. This mirrors the Dataminr
    agentic-search architecture: one service, two transports, zero duplication.

    HTTP mapping (informational — REST is handled by FastAPI, not grpc-gateway):
    GET /api/v1/cryptocurrencies/{coin_id}/insight
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInsight = channel.unary_unary(
                '/crypto.insight.v1.InsightService/GetInsight',
                request_serializer=crypto_dot_insight_dot_v1_dot_insight__pb2.GetInsightRequest.SerializeToString,
                response_deserializer=crypto_dot_insight_dot_v1_dot_insight__pb2.GetInsightResponse.FromString,
                _registered_method=True)


class InsightServiceServicer(object):
    """InsightService generates AI-powered price trend analysis for cryptocurrencies.

    Dual-protocol pattern: this service is exposed via both:
    gRPC  — port 50051 (this file)
    REST  — port 8000  (FastAPI /api/v1/cryptocurrencies/{coin_id}/insight)

    Both transports share identical business logic. This mirrors the Dataminr
    agentic-search architecture: one service, two transports, zero duplication.

    HTTP mapping (informational — REST is handled by FastAPI, not grpc-gateway):
    GET /api/v1/cryptocurrencies/{coin_id}/insight
    """

    def GetInsight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InsightServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInsight': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInsight,
                    request_deserializer=crypto_dot_insight_dot_v1_dot_insight__pb2.GetInsightRequest.FromString,
                    response_serializer=crypto_dot_insight_dot_v1_dot_insight__pb2.GetInsightResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crypto.insight.v1.InsightService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crypto.insight.v1.InsightService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InsightService(object):
    """InsightService generates AI-powered price trend analysis for cryptocurrencies.

    Dual-protocol pattern: this service is exposed via both:
    gRPC  — port 50051 (this file)
    REST  — port 8000  (FastAPI /api/v1/cryptocurrencies/{coin_id}/insight)

    Both transports share identical business logic. This mirrors the Dataminr
    agentic-search architecture: one service, two transports, zero duplication.

    HTTP mapping (informational — REST is handled by FastAPI, not grpc-gateway):
    GET /api/v1/cryptocurrencies/{coin_id}/insight
    """

    @staticmethod
    def GetInsight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crypto.insight.v1.InsightService/GetInsight',
            crypto_dot_insight_dot_v1_dot_insight__pb2.GetInsightRequest.SerializeToString,
            crypto_dot_insight_dot_v1_dot_insight__pb2.GetInsightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
